name             'ubuntu-baseline'
maintainer       'Jason Stirk'
maintainer_email 'jason@oobleyboo.com'
license          'MIT, (c) 2014 Jason Stirk. See LICENCE.md'
description      'Basic setup and security hardening for an Ubuntu server'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.4.0'

depends 'user', '~> 0.3.0'
depends 'openssh', '~> 1.1.4'
depends 'sudo', '~> 2.6.0'
depends 'ntp', '~> 1.6.4'
depends 'simple_iptables', '~> 0.2.4'
depends 'swap', '~> 0.3.6'
depends 'timezone'
